### ISSUE TITLE
Client issue

### ISSUE THREAD

**Issue by SplitGemini** [jurihock/reopen62541#1]
How can I know the variant type before read a node?

**Comment by jurihock** [comment]
That's easy, the client just need to know the specific variant type to be accessed, just by convention of your specific protocol.

E.g. if there is a variable "MyVariable" of type "int", the server provides it `server.add_variable<int>("MyVariable", ...)` and the client accesses it `client.get<int>("MyVariable", ...)`.

Just study the calculator example in the examples folder.

**Comment by SplitGemini** [comment]
What if the server that not configured by myself?

**Comment by jurihock** [comment]
1. Kindly ask the OPC service provider
2. Use [UaExpert](https://www.unified-automation.com/products/development-tools/uaexpert.html) to browse the OPC service features
3. Finally study the [open62541](http://www.open62541.org) manual
4. Use the origin open62541 API, if **re**open62541 isn't suitable
5. Ask open62541 community for OPC and open62541 related questions, since I'm not an OPC expert

Good luck!

**Comment by SplitGemini** [comment]
Thanks.

**Comment by SplitGemini** [comment]
By the way, here [src/reopen62541/client.cpp#L130](https://github.com/jurihock/reopen62541/blob/b1b38cce93657843e0b319c790f26f8ff3b83cea/src/reopen62541/client.cpp#L130) should be a bug, maybe should be a  'read' here.
